experiment_name: leaf_class
suffix: 'pretrained_2_resume'

device_id: [7,8]

model: resnet18
pretrained: True

epochs: 300
batch_size: 512
learning_rate: 0.000005
num_classes: 176

weight_decay: 0.0001

resume: True
checkpoint_path: 'logs/leaf_class_resnet18_pretrained_2_resume/model150.pth'

save_interval: 10