experiment_name: leaf_class
suffix: '1'

device_id: [0]

model: resnet18
pretrained: False

epochs: 50
batch_size: 128
learning_rate: 0.01
num_classes: 176

weight_decay: 0.0001

resume: False
checkpoint_path: None

save_interval: 5